#@copyright : abdallah_ahmed
CC=arm-none-eabi-
CFLAGS=-g -mcpu=cortex-m4 -gdwarf-2  -g  
INCS=-I .
LIBS=
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As= $(wildcard *.s)
AsOBJ=$(As:.s=.o)
Project_name=unit3_lab4_cortexM4

all:$(Project_name).hex


	$(CC)as.exe  $(CFLAGS) $< -o $@
%.o:%.c
	$(CC)gcc.exe -c  $(CFLAGS) $(INCS) $< -o $@

$(Project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld -T linker_script.ld $(LIBS)$(OBJ) $(AsOBJ) -o $@ -Map=Map_file.map
	cp $(Project_name).elf  $(Project_name).axf 
$(Project_name).hex:	$(Project_name).elf
	$(CC)objcopy.exe -O binary $<  $@
	
clean_all:
	
	rm *.o *.elf *.bin
clean:
	rm *.elf *.bin